### ISSUE TITLE
Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by stuartjeasyodds** [Pushwoosh/pushwoosh-react-native-plugin#10]
I am getting the following error in the PWEventDispatcher.h file:

![screen shot 2017-03-28 at 12 48 23](https://cloud.githubusercontent.com/assets/21107440/24403461/daeb9584-13b4-11e7-83ec-67e42a9eadb0.png)

#import <React/RCTBridge.h>

react-native-cli: 2.0.1
react-native: 0.37.0

**Comment by DimanAM** [comment]
Backwards compatibility of native modules was broken since react-native 0.40.0 release https://github.com/facebook/react-native/releases/tag/v0.40.0.
Consider updating react-native to the latest version or you will have to use old versions of modules (e.g pushwoosh-react-native-plugin 2.0.0 should be compatible with RN < 0.40.0).

**Comment by stuartjeasyodds** [comment]
I am using version 1.2.5:

  ```
"dependencies": {
    "@exponent/ex-navigation": "^2.7.1",
    "axios": "^0.15.2",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "bugsnag-react-native": "^1.1.3",
    "moment": "^2.17.0",
    "pushwoosh-react-native-plugin": "^1.2.5",
    "react": "15.3.2",
    "react-native": "0.37.0",
    "react-native-animatable": "^0.6.1",
    "react-native-appsflyer": "^1.0.10",
    "react-native-browser": "^0.6.2",
    "react-native-cli": "^2.0.1",
    "react-native-device-info": "^0.9.9",
    "react-native-google-analytics-bridge": "^4.0.2",
    "react-native-looped-carousel": "^0.1.4",
    "react-native-star-rating": "^1.0.6",
    "react-native-vector-icons": "^3.0.0",
    "react-native-youtube": "^0.8.0",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-thunk": "^2.1.0"
  },
```

**Comment by JanithaR** [comment]
Hi, I have
```
"pushwoosh-react-native-plugin": "^5.8.0",
"react-native": "0.55.3"
```
and getting this error. How am I suppose to figure out which version of pushwoosh-react-native-plugin I should be using? Downgrading react-native from 0.55.3 is not an option.

**Comment by stereodenis** [comment]
@DimanAM 
got the same on 0.60.0

**Comment by JanithaR** [comment]
> @DimanAM
> got the same on 0.60.0

If you run into issues like this with pushwoosh-react-native-plugin or any other module for that matter just do,
`rm -rf node_modules && npm install`

**Comment by wfhm** [comment]
@stereodenis If solution offered by @JanithaR does not solve your problem, may I ask you to create a new issue in this repo? Our tracking system does not check issues created before May, 2019, so I have almost missed this update.
