### ISSUE TITLE
Xcode Build Error on 5.20.8 after updating to latest version 

### ISSUE THREAD

**Issue by CallmeKingsley** [Pushwoosh/pushwoosh-react-native-plugin#100]
After getting a message from apple store connect about "ITMS-90809: Deprecated API Usage - apple will no longer accept submission of new apps that UiWebView as of April 30, 2020."

I updated to the latest version of pushwoosh-react-native-plugin version 5.20.8 

i ran 'grep -r UIWebView ios/Pods/'
to check if UiWebView still exist in the directory
![Screen Shot 2020-04-30 at 12 50 55 PM](https://user-images.githubusercontent.com/24882097/80737468-8ca32c00-8ae1-11ea-8df8-2ebfd075fa92.png)
   
when I try to  make a build on Xcode, I get those error 
![Screen Shot 2020-04-30 at 10 36 17 AM](https://user-images.githubusercontent.com/24882097/80736205-cc691400-8adf-11ea-8b08-27d141f998a0.png)

any solution will be appreciated.

**Comment by wfhm** [comment]
Hi @CallmeKingsley,

Pushwoosh SDK was migrated to WKWebView in the 5.19.1 release of the native iOS SDK, so it looks like you use an outdated Titanium plugin. Could you please try updating to the latest version and let us know about the results?

**Comment by CallmeKingsley** [comment]
Thanks for the quick response. how do I update my Titanium plugin cause i believe am already in the latest version of Pushwoosh when I ran "npm install pushwoosh-react-native-plugin --save"

**Comment by wfhm** [comment]
@CallmeKingsley,

That should install the latest version, but could you please check which particular version is added to your project? It should be 5.20.8 for the latest React Native plugin version.

**Comment by CallmeKingsley** [comment]
![Screen Shot 2020-04-30 at 5 12 47 PM](https://user-images.githubusercontent.com/24882097/80759780-db62bd00-8b05-11ea-95d7-8e0f54b868b2.png)

that's the version on my package.json file

**Comment by wfhm** [comment]
@CallmeKingsley okay, thanks for the details. Please let me pull some time to check it and I will be back shortly

**Comment by CallmeKingsley** [comment]
@wfhm I believe I have resolved the issue.
1) I revert to the old version and ran "npm update pushwoosh-react-native-plugin"
2) I deleted podfile.lock file,Pods folder and node_modules folder for  fresh references 
3) I ran yarn/npm install, then I went to the ios folder and ran pod install

It looks like works now. thanks @wfhm

**Comment by wfhm** [comment]
@CallmeKingsley,

That should do the trick, good job!
