### ISSUE TITLE
To what extent is Firebase required for this plugin?

### ISSUE THREAD

**Issue by danielimmke** [Pushwoosh/pushwoosh-react-native-plugin#102]
The instructions say to configure Firebase, but is that only needed for Android?

**Comment by danielimmke** [comment]
Also, since it looks like you added a support ticket number to this: I can't get test notifications sending to my physical device (iOS) I followed the example code from the repo and was able to get a Device Token (which confirmed to me that my `pw_appid` and `project_number` are correct.  Because when they weren't it wouldn't give me one) I registered as a Test Device in Push Woosh.

I have Push Notifications turned on in XCode.

Even the subscriber count increments by one - so PushWoosh knows about my device and notifications are allowed. Do you know of any other reason why notifications wouldn't be sending?

Do I need to actually implement the Pushwoosh SDKs in addition to implementing the React Native plugin? The example repo didn't seem to have that.

This is my index.js:

`AppRegistry.registerComponent(appName, () => App); // Regular app component

Pushwoosh.init({ "pw_appid" : "###", "project_number":"###"});

DeviceEventEmitter.addListener('pushOpened', (e: Event) => {
  console.warn("pushOpened: " + JSON.stringify(e));
  alert(JSON.stringify(e));
});

Pushwoosh.register(
  (token) => {
    console.warn("Registered for pushes: " + token);
    Pushwoosh.getPushToken(function(token) {
        console.warn("Push token: " + token);
    });
  },
  (error) => {
    console.warn("Failed to register: " + error);
  }
);`

**Comment by wfhm** [comment]
@danielimmke,

Yes, Firebase configuration is required for Android only. The support ticket is indeed added to a Github issue, however, it is only done for the support team to be aware of the issues reported here. The issues like yours are to be reported directly to our support at https://help.pushwoosh.com/hc/en-us/requests/new, as we will need your account name and application ID, which should not be exposed in a public thread. Could you please contact us via the form above and describe the issue in detail?
