### ISSUE TITLE
build.gradle Needs updating?

### ISSUE THREAD

**Issue by danielimmke** [Pushwoosh/pushwoosh-react-native-plugin#103]
Should these numbers be updated? Building an apk failed for me until I changed them. https://github.com/Pushwoosh/pushwoosh-react-native-plugin/blob/master/src/android/build.gradle

_Originally posted by @danielimmke in https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/86#issuecomment-631025614_

**Comment by wfhm** [comment]
@danielimmke 

The version numbers might need to be changed, for example, if there is a conflict between several plugins in your app. Could you please share the build error log?
