### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by LiamGregory** [Pushwoosh/pushwoosh-react-native-plugin#105]
when doing a pod install on pushwoosh 5.20.8 it pulls in 
these old version of the pushwoosh sdk 

Installing Pushwoosh (5.19.1)
Installing PushwooshInboxUI (5.16.0)

according to this issue on the ios SDK repo 5.19.1 still contains UIWebView
https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/83

**Comment by wfhm** [comment]
@LiamGregory,

Did you try running `pod update` and rebuilding the app already?

**Comment by mickamy** [comment]
I think it is nice to specify original Pushwoosh SDK version in podspec file.

**Comment by mickamy** [comment]
@LiamGregory 
I think not providing dependent SDK version is a bit confusing.
What do you think about this PR? https://github.com/Pushwoosh/pushwoosh-react-native-plugin/pull/118
