### ISSUE TITLE
ios - build failed - "Use of undeclaredidentifier 'Pushwoosh'"

### ISSUE THREAD

**Issue by Or-B** [Pushwoosh/pushwoosh-react-native-plugin#109]
Hi,
there is a problem at Pushwoosh.m file in these lines:
if (proxyUrl && config[@"reverse_proxy_url"]){
   [[**Pushwoosh** sharedInstance] setReverseProxy:proxyUrl];
}

you need to replace **Pushwoosh** by **PushwooshPlugin**

**Comment by wfhm** [comment]
@Or-B checking it

**Comment by wfhm** [comment]
@Or-B 

I could not reproduce it. `PushwooshPlugin` class does not have the `setReverseProxy` method, but `Pushwoosh` class does (was added with the 6.0.5 version of Pushwoosh iOS SDK). Could you please check whether Pushwoosh iOS SDK is resolved to 6.0.5 version, and, if not, try running `pod repo update`, then `pod update`.

**Comment by rogerroelofs** [comment]
That resolved it for me.
