### ISSUE TITLE
pushOpened event not fired on ANDROID

### ISSUE THREAD

**Issue by omarcarreon** [Pushwoosh/pushwoosh-react-native-plugin#11]
I have a similar issue as #6 but in my case it's not working on Android. 

On iOS I'm using this method and it's currently working:

```js
Pushwoosh.onPushOpen(_pushHandler);
```
but on Android I've tried that method and also the DeviceEventEmitter:
```js
DeviceEventEmitter.addListener('pushOpened', _pushHandler); 
```
but they're not firing.

Does anyone know what could be the problem?
 
Thanks for your help in advance

I'm using "react-native": "0.41.2" and "pushwoosh-react-native-plugin": "^3.0.2"

**Comment by wfhm** [comment]
Fixed in [3.0.3](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/3.0.3).
