### ISSUE TITLE
programmatically mark notification opened

### ISSUE THREAD

**Issue by Blerr511** [Pushwoosh/pushwoosh-react-native-plugin#114]
how can I programmatically mark notification opened

**Comment by wfhm** [comment]
@Blerr511,

Could you please describe your use-case in a bit more detail? Do you want to mark a notification as opened in your inbox, or do you want to automatically open a received notification to remove it from the notification center and handle its payload? It would be really helpful if you could provide as many details as possible so we could suggest you the best solution.

**Comment by Blerr511** [comment]
@wfhm 
I need to store my push notifications into inbox , but when I refresh app - every time I'm getting last notification and it's adding into inbox every time , how I can prevent that ? I'm using TV os and there is no way to manually remove notification from notification bar or click on it to open

**Comment by Blerr511** [comment]
Nevermind , problem was only when I reload app from dev menu , when I stop application and run again there is no problem
