### ISSUE TITLE
Will pushwoosh work on huawei devices without firebase/google support

### ISSUE THREAD

**Issue by SimonErich** [Pushwoosh/pushwoosh-react-native-plugin#116]
Will this pushwoosh package work just as intended on these devices without google services, or will there be a problem or an alternative package?
I noticed, that a pushwoosh-huawei android native library was published a few days ago.
Does this react-native package support this already?

**Comment by wfhm** [comment]
@SimonErich,

Native SDK works on Huawei devices just fine. The plugins still have to be updated to reflect these changes. React Native plugin does not work on devices without google services right now.

**Comment by SimonErich** [comment]
@wfhm do you have a timeline, when pushwoosh will be supported on Huawei devices using hms with the react-native plugin?

**Comment by wfhm** [comment]
@SimonErich,

There is no ETA right now, however, we expect to start working on plugin updates in the second half of December, and React Native is on top of the list. I will provide a precise ETA once there is any.

**Comment by wfhm** [comment]
@SimonErich,

HMS support is added with the 6.1.0 version.
