### ISSUE TITLE
Notifications with link on iOS opens the app but not the link

### ISSUE THREAD

**Issue by lampkap** [Pushwoosh/pushwoosh-react-native-plugin#117]
I'm trying to send a push notification with a deep link but the link never gets handled on iOS. When a push notification with a link is tapped, it opens the app but it never opens the link (neither with a https url or a deep link). Both when the app is in background or already opened. This only affects iOS, it works fine on Android.

I've followed the instructions [here](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/integrating-react-native-plugin) for integrating Pushwoosh with my app. I'm running React Native version 0.61.5 and Pushwoosh plugin version 6.0.6 and my device is running iOS 14. I've also tried upgrading the Pushwoosh plugin to the latest version but to no avail.

I've then tried to implement a workaround using the `pushOpened` event with both `DeviceEventEmitter` and `NativeEventEmitter`, but the callback never gets called on iOS (neither for the `pushReceived` event). I've tested this with both local push notifications and notifications sent with the api (/createMessage). 

My next step was to test this with [the example provided in the README.md](https://github.com/Pushwoosh/pushwoosh-react-native-sample). After I cloned the example and updated the Pushwoosh plugin (I was getting an error that the interface already has been declared on version 5.15.2. After upgrading to 6.0.9, the app built successfully), the events were also never called on iOS for local push notifications. 

Am I missing something in the integration of the plugin?

Thanks for your response!

**Comment by wfhm** [comment]
@lampkap,

I could not reproduce the issue so far, so could you please share a reproducer? Also, can you give an example of the link you use?


> I've then tried to implement a workaround using the `pushOpened` event with both `DeviceEventEmitter` and `NativeEventEmitter`, but the callback never gets called on iOS (neither for the `pushReceived` event). I've tested this with both local push notifications and notifications sent with the api (/createMessage).


Local notifications are not triggering these callbacks, they are designed to work only with push notifications. Did you try it with pushes? Also, can you share your implementation of the callbacks in your code?

**Comment by lampkap** [comment]
@wfhm 

Thanks for your quick response!

I've got it working on a different Pushwoosh application and compared the two applications. It seems that the only difference between the two is that one has been configured with the framework "Native" under iOS and the other one (the working one) is configured with "React Native".

**Comment by wfhm** [comment]
@lampkap,

The framework field in the configuration tab is used only for our internal statistics, it does not actually affect anything in our SDK or backend. Perhaps, there was something else in the project, however, it is really hard to say now. Please feel free to reopen the issue shall you have the same issue again.
