### ISSUE TITLE
There is no way to know if the event is in foreground or not

### ISSUE THREAD

**Issue by feliara8** [Pushwoosh/pushwoosh-react-native-plugin#12]
Hi, we are using version 3.0.2, and theres no data in the event, to know if the app is closed or open.
Is this intended?

**Comment by wfhm** [comment]
Hi,

Pushwoosh React Native plugin does not currently provide this functionality. Could you please describe a use-case that you want to solve with this functionality? How do you want to use it in your app?

**Comment by wfhm** [comment]
@feliara8 

Is there any news on this request?
