### ISSUE TITLE
How to set the device timezone?

### ISSUE THREAD

**Issue by taschik** [Pushwoosh/pushwoosh-react-native-plugin#120]
We want to make sure our users only receive pushes at a given local time. The user explorer, however, shows us that non of our registered devices have a timezone set. 
<img width="1038" alt="Screen Shot 2021-02-02 at 4 43 56 PM" src="https://user-images.githubusercontent.com/351623/106681753-fd4a0e00-6575-11eb-8d2d-ffaf0132a458.png">

How can we set the timezone via the SDK or shouldn't this be done automatically?

**Comment by taschik** [comment]
HI @wfhm do you have any insight on this?

**Comment by wfhm** [comment]
@taschik,

Timezone values are actually collected by our SDK and sent to our backend automatically, however, it looks like they are not passed to the User Explorer correctly. Checking it with the backend team now.

**Comment by taschik** [comment]
Thanks @wfhm for checking back. The reason I was asking is that I couldn't see that information anywhere in the UI panels of Pushwoosh and wanted to make sure we can still respect silent hours (e.g. at night) meaning that pushes will not be send at certain times for certain time zones. Is this still working?

**Comment by wfhm** [comment]
@taschik,

Sure, everything is fine with the timezone pushes right now.

**Comment by taschik** [comment]
Thanks for confirming!
