### ISSUE TITLE
Build error from nowhere

### ISSUE THREAD

**Issue by Ifritzz** [Pushwoosh/pushwoosh-react-native-plugin#126]
Package Version: 6.1.5
React Native Version: 0.63.3

Hi! 

After making no changes at all, today we are facing an error when we try to build an Android .apk. Last week, with exactly the same configuration, everything was working fine.

We are experiencing the following error:

`Execution failed for task ':pushwoosh-react-native-plugin:verifyReleaseResources'.`

Our build.gradle settings:

`buildToolsVersion = 29.0.2
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29`

We have tried to upgrade the build grade settings to 30 for tools and sdkversions, we have tried to build it with ./gradlew assembleRelease and ./gradlew app:assembleRelease. We have even tried to set manually the plugin version to align it with the project sdk's version (even being a bad practice).

I have attached the full log for checking purposes.

[error log.txt](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/files/7116778/error.log.txt)

**Comment by wfhm** [comment]
@Ifritzz,

Will be fixed with the next release. Meanwhile, you can use the workaround with updated gradle settings you described.

**Comment by Ifritzz** [comment]
Hi @wfhm , I have described a workaround I've found but, in our case, is not working (or we are implementing it wrong). Can you please describe a 'how to'?

Thanks

**Comment by wfhm** [comment]
@Ifritzz,

Should be fixed with the latest release.
