### ISSUE TITLE
android problem , crush on app after build successfully 

### ISSUE THREAD

**Issue by morelgarisi** [Pushwoosh/pushwoosh-react-native-plugin#127]
after upgrading to 61.5 react native version , 
and update the pushwhoosh plugin     "pushwoosh-react-native-plugin": "^6.1.5",

the app build succesfully on android but crushes when opened 
keep getting : Pushwoosh: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.

adb log:

9-13 12:06:45.304 10899 10899 E Pushwoosh: This is not an Amazon device. The service is not available.
09-13 12:06:45.307 10899 10899 E Pushwoosh: [HuaweiUtils] Huawei HMS Core SDK - Push Kit not integrated. Follow the guide to integrate the library to your project https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/android-integrating-sdk-0000001050040084-V5
09-13 12:06:45.307 10899 10899 E Pushwoosh: This is not a Huawei device. The service is not available.
09-13 12:06:45.311 10899 10927 D Pushwoosh: [CrashAnalytics] Looking for exceptions in: /data/user/0/com.moonsite.hicar/files
09-13 12:06:45.314 10899 10918 W .moonsite.hica: Unsupported class loader
09-13 12:06:45.330 10899 10918 W .moonsite.hica: Skipping duplicate class check due to unsupported classloader
09-13 12:06:45.371 10899 10934 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-13 12:06:45.413 10899 10899 I Pushwoosh: Log level: DEBUG
09-13 12:06:45.413 10899 10899 D Pushwoosh: [PushRegistrarHelper] Initializing default PushRegistrar in a plugin
09-13 12:06:45.414 10899 10899 E Pushwoosh: This is not an Amazon device. The service is not available.
09-13 12:06:45.414 10899 10899 E Pushwoosh: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
09-13 12:06:45.414 10899 10899 E Pushwoosh: Check documentation for more info https://goo.gl/UVJKfp
09-13 12:06:45.414 10899 10899 E Pushwoosh: [PushRegistrarHelper] Unexpected error occurred calling 'initRegistrarClass' method
09-13 12:06:45.414 10899 10899 E Pushwoosh: [PushRegistrarHelper] You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
09-13 12:06:45.414 10899 10899 E Pushwoosh: Check documentation for more info https://goo.gl/UVJKfp
09-13 12:06:45.415 10899 10899 E Pushwoosh: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
09-13 12:06:45.415 10899 10899 E Pushwoosh: Check documentation for more info https://goo.gl/UVJKfp
09-13 12:06:45.415 10899 10899 D AndroidRuntime: Shutting down VM
09-13 12:06:45.420 10899 10899 E AndroidRuntime: FATAL EXCEPTION: main
09-13 12:06:45.420 10899 10899 E AndroidRuntime: Process: com.moonsite.hicar, PID: 10899
09-13 12:06:45.420 10899 10899 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
09-13 12:06:45.420 10899 10899 E AndroidRuntime: Check documentation for more info https://goo.gl/UVJKfp
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.
09-13 12:06:45.420 10899 10899 E AndroidRuntime: Check documentation for more info https://goo.gl/UVJKfp
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.firebase.internal.checker.FirebaseChecker.check(Unknown Source:15)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.firebase.internal.registrar.FcmRegistrar.init(Unknown Source:5)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.notification.PushwooshNotificationManager.d(Unknown Source:2)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.d.a(Unknown Source:59)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.PushwooshPlatform.l(Unknown Source:2)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.PushwooshInitializer.init(Unknown Source:67)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:18)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	... 10 more
09-13 12:06:45.420 10899 10899 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.firebase.iid.FirebaseInstanceId
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:453)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:378)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at com.pushwoosh.firebase.internal.checker.FirebaseChecker.check(Unknown Source:2)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	... 19 more
09-13 12:06:45.420 10899 10899 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.moonsite.hicar-8Vedu_KXgp7Rzb2wq73K_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.moonsite.hicar-8Vedu_KXgp7Rzb2wq73K_w==/lib/x86, /data/app/com.moonsite.hicar-8Vedu_KXgp7Rzb2wq73K_w==/base.apk!/lib/x86, /system/lib]]
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-13 12:06:45.420 10899 10899 E AndroidRuntime: 	... 23 more
09-13 12:06:45.423  1825  1954 W ActivityManager:   Force finishing activity com.moonsite.hicar/.MainActivity
09-13 12:06:45.446  1825  1843 I ActivityManager: Showing crash dialog for package com.moonsite.hicar u0
09-13 12:06:45.448  1825  1840 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-13 12:06:45.448  1825  1840 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-13 12:06:45.516  1697  1706 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
09-13 12:06:45.529  1583  1625 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3252224
09-13 12:06:45.533  2523  2550 E s.nexuslaunche: No package ID ff found for ID 0xffffffff.
09-13 12:06:45.533  2523  2550 E IconLoader: Could not find icon drawable from resource
09-13 12:06:45.533  2523  2550 E IconLoader: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
09-13 12:06:45.533  2523  2550 E IconLoader: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at android.content.res.Resources.getDrawable(Resources.java:827)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
09-13 12:06:45.533  2523  2550 E IconLoader: 	at android.os.Binder.execTransact(Binder.java:731)
09-13 12:06:45.536  1684  1717 D         : HostConnection::get() New Host Connection established 0xf2e18200, tid 1717
09-13 12:06:45.537  1583  1583 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3252224
09-13 12:06:45.540  1583  1583 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3252224
09-13 12:06:45.548  1825  8623 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
09-13 12:06:45.548  1825  8623 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
09-13 12:06:45.548  1825  8623 I OpenGLRenderer: Initialized EGL, version 1.4
09-13 12:06:45.548  1825  8623 D OpenGLRenderer: Swap behavior 1
09-13 12:06:45.548  1825  8623 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
09-13 12:06:45.548  1825  8623 D OpenGLRenderer: Swap behavior 0
09-13 12:06:45.552  1825  8623 D EGL_emulation: eglCreateContext: 0xcb2c0040: maj 3 min 0 rcv 3
09-13 12:06:45.554  1825  8623 D EGL_emulation: eglMakeCurrent: 0xcb2c0040: ver 3 0 (tinfo 0xd21f07e0)
09-13 12:06:45.599  1825  8623 D EGL_emulation: eglMakeCurrent: 0xcb2c0040: ver 3 0 (tinfo 0xd21f07e0)
09-13 12:06:45.600 10899 10942 I FA      : App measurement initialized, version: 42082
09-13 12:06:45.600 10899 10942 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
09-13 12:06:45.600 10899 10942 I FA      : To enable faster debug mode event logging run:
09-13 12:06:45.600 10899 10942 I FA      :   adb shell setprop debug.firebase.analytics.app com.moonsite.hicar
09-13 12:06:45.694  2287  2287 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
09-13 12:06:45.694  2287  2287 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
09-13 12:06:45.709  1825  1843 W Looper  : Slow dispatch took 160ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@409cbc6 m=0
09-13 12:06:45.743 10899 10942 I FA      : Tag Manager is not found and thus will not be used
09-13 12:06:45.905  1825  2681 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@8a05cef)
09-13 12:06:45.906  1825  1839 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@8a05cef)
09-13 12:06:45.926  1825  1840 W ActivityManager: Activity pause timeout for ActivityRecord{446692f u0 com.moonsite.hicar/.MainActivity t20 f}
09-13 12:06:45.987  1960  2212 D EGL_emulation: eglMakeCurrent: 0xec784780: ver 3 0 (tinfo 0xec783520)
09-13 12:06:46.113  1960  2212 I chatty  : uid=10028(com.android.systemui) RenderThread identical 10 lines
09-13 12:06:46.127  1960  2212 D EGL_emulation: eglMakeCurrent: 0xec784780: ver 3 0 (tinfo 0xec783520)
09-13 12:06:46.910  1825  2681 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@7576694)
09-13 12:06:46.910  1825  1839 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@7576694)
09-13 12:06:47.323  1825  1850 D KernelUidCpuTimeReader: Removing uids 10128-10128
09-13 12:06:47.808  1573  1657 W audio_hw_generic: Not supplying enough data to HAL, expected position 3450184 , only wrote 3296880
09-13 12:06:47.914  1825  2681 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@beff53d)
09-13 12:06:47.914  1825  1839 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@beff53d)

**Comment by wfhm** [comment]
@morelgarisi Should be fixed in the 6.1.6 version. Could you please try updating to the latest version and let us know about the results?
