### ISSUE TITLE
Duplicate declaration of method 'clearLocalNotification'

### ISSUE THREAD

**Issue by morelgarisi** [Pushwoosh/pushwoosh-react-native-plugin#130]
![Uploading Screen Shot 2021-11-28 at 13.28.14.png…]()
![Screen Shot 2021-11-28 at 13 36 34](https://user-images.githubusercontent.com/18554479/143766099-7bf5118c-9c1d-4d56-9db8-b32f212e666d.png)

**Comment by wfhm** [comment]
@morelgarisi thanks for reporting this, will be fixed shortly.

**Comment by morelgarisi** [comment]
> @morelgarisi thanks for reporting this, will be fixed shortly.

omg! thank you!!!

**Comment by wfhm** [comment]
@morelgarisi fixed in 6.1.10.
