### ISSUE TITLE
Feature: deleteTag method

### ISSUE THREAD

**Issue by fmacherey** [Pushwoosh/pushwoosh-react-native-plugin#133]
Hey guys, 

it looks like the `deleteTag` method is missing in this packages, but is supported by the REST-API. Could you please provide this method? 

Thanks

**Comment by wfhm** [comment]
Hi @fmacherey 

This is actually not there for a reason - the **/deleteTag** API method is used for deleting the tag itself from your Pushwoosh account, not for clearing its value for a particular device, so it is not related to the SDK functionality at all.

If you want to clear a Tag value from a device, you can just set its value as an empty string.
