### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by stanwrkt** [Pushwoosh/pushwoosh-react-native-plugin#134]
Hello, could you please add M1 arch support for the pod?
Currently the build fails with the following error:
`Building for iOS Simulator, but linking in object file built for iOS`

I found this [issue](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/122), but excluding arm64 is not an option. It can work only if you run Xcode via Rosetta.

Thanks.

**Comment by wfhm** [comment]
@stanwrkt Checking it.

**Comment by wfhm** [comment]
@stanwrkt got it reproduced, it will be fixed with the next release.

**Comment by wfhm** [comment]
@stanwrkt Should be fixed in 6.1.13.
