### ISSUE TITLE
fail on load : null is not an object (evaluating 'PushwooshModule.init') (Expo Project)

### ISSUE THREAD

**Issue by nympheastudio** [Pushwoosh/pushwoosh-react-native-plugin#140]
i  installed and linked the last version of the plugin on my project, but i get this error  on app load
```

TypeError: null is not an object (evaluating 'PushwooshModule.init')

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

my package.json is like 

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@react-native-community/datetimepicker": "^6.1.3",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/material-bottom-tabs": "^5.2.16",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "axios": "^0.26.0",
    "expo": "~43.0.2",
    "expo-camera": "^12.1.2",
    "expo-image-manipulator": "^10.2.1",
    "expo-location": "^14.0.2",
    "expo-media-library": "^14.0.1",
    "expo-permissions": "^13.1.1",
    "expo-status-bar": "~1.1.0",
    "formik": "^2.2.9",
    "js-cookie": "^3.0.1",
    "moment": "^2.29.3",
    "pushwoosh-react-native-plugin": "^6.1.14",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-paper": "^4.0.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-section-alphabet-list": "^2.1.0",
    "react-native-tab-view": "^2.15.1",
    "react-native-vector-icons": "7.1.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "^11.17.2",
    "typescript": "^4.3.5",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true,
  "version_app": "2.0.0"
}

is this RN pushwoosh plugin  is compatible with EXPO Project ?

thanks

**Comment by wfhm** [comment]
@nympheastudio Expo is not supported by the plugin right now, we plan to add is support, but I cannot provide you with an ETA at this moment.

**Comment by nympheastudio** [comment]
ok thanks, so for now i ll use expo push, thanks
