### ISSUE TITLE
Android | Notification not appearing in notification bar / status bar 

### ISSUE THREAD

**Issue by sujit-libi** [Pushwoosh/pushwoosh-react-native-plugin#146]
I have integrated pushwoosh sdk for react native application. Since when we trigger notification from pushwoosh dashboard we are getting data to log only but notification not appearing. Silent push is false in my case but it is acting as slient push notification. Data can be seen in log using setBackgroundMessageHandler() but no notification appear in notification bar.

in logger: 

`{"collapseKey": "3A6D-D2B238CF-3F48947E", "data": {"delivery_priority": "high", "header": "Test Notification😍", "md": "{\"_mc\":\"3A6D-D2B238CF-3F48947E\",\"user_id\":\"de6a2ec6-880b-4fd3-8efc-138c48b5c079\"}", "p": "dqft!KB-q9", "pri": "2", "pw_msg": "1", "s": "default", "title": "Test Notification😍", "vib": "0"}, "from": "729826958634", "messageId": "0:1672319650945834%eb28039d59ad3476", "sentTime": 1672319650939, "ttl": 604800}`

**Comment by Techsorcist** [comment]
Hi @sujit-libi,
Most likely, the other Firebase Messaging Service implementations exist alongside Pushwoosh, but with higher priority. The `FirebaseMessagingService` is responsible for handling push notifications when they are received. However, only the one with the highest priority will work.

You have to check if `com.pushwoosh.firebase.PushFcmIntentService` in the **AndroidManifest.xml** has the highest priority to handle all pushes using `android:priority` inside `<intent-filter>` or just place it above others (in case the "priority" is not specified).
