### ISSUE TITLE
setTags doesn't work on Android

### ISSUE THREAD

**Issue by aknad** [Pushwoosh/pushwoosh-react-native-plugin#15]
I can register the device and then the setTags function return a success callback
but when I check my tag in the control panel or with the getTags function I can't see it

**Comment by wfhm** [comment]
Hi,

Could you please check your device log and let us know whether you can find a /setTags API call being sent? There should be something like that:

>   x
                                                              |     Pushwoosh request:
                                                              | Url: https://7559E-DE020.api.pushwoosh.com/json/1.3/setTags
                                                              | Payload: {“request”:{“application”:“7559E-DE020”,“hwid”:“7d15246a9dac9491”,“v”:“5.1.1”,“device_type”:3,“userId”:“7d15246a9dac9491",“tags”:{“testTag”:“testValue”}}}
                                                              | Response: {“status_code”:200,“status_message”:“OK”,“response”:{“skipped”:[{“tag”:“testTag”,“reason”:“Not found”}]}}
                                                              x

What is the response you get for this request? If you don't have this request logged, please share your code for sending Tags.

**Comment by aknad** [comment]
here my log:

> | Pushwoosh request:
> | Url: https://XXXXX-XXXXX.api.pushwoosh.com/json/1.3/setTags
> | Payload: {"request":{"application":"XXXXX-XXXXX","hwid":"8406ba41787e3f43","v":"5.1.1","device_type":3,"userId":"8406ba41787e3f43","tags":{"Channels":"recipe_free_it_afternoon"}}}
> Response: {"status_code":200,"status_message":"OK","response":{"skipped":[]}}
> x
> Pushwoosh request:
> Url: https://XXXXX-XXXXX.api.pushwoosh.com/json/1.3/getTags
> Payload: {"request":{"application":"XXXXX-XXXXX","hwid":"8406ba41787e3f43","v":"5.1.1","device_type":3,"userId":"8406ba41787e3f43"}}
> Response: {"status_code":200,"status_message":"OK","response":{"result":{"Language":"it","Country":"it","City":"it, milan","Application Version":"4.0.0","Last Application Open":1507680000,"First Install":1507680000}}}
> x

**Comment by wfhm** [comment]
@aknad We could not reproduce the issue on our side. May I ask you to contact our support team via [this form](https://www.pushwoosh.com/contact-us/) and provide them with your application ID and account name so we could check what is happening with Tags on your account?

**Comment by wfhm** [comment]
@aknad 

Could you please let us know whether you had a chance to contact our Support Team?

**Comment by aknad** [comment]
@wfhm 
yes, sorry for the delay
the problem was that my tag is configured as array and I set a string
I don't know why on IOS it works but doesn't matter, using an array it works on both OS
thanks
