### ISSUE TITLE
[Bug]: Push Notifications not working at all on iOS

### ISSUE THREAD

**Issue by AlbinNewSeed** [Pushwoosh/pushwoosh-react-native-plugin#157]
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

Registering for push works, and token is received but when I try and register token on test device, it says "Device not found by push token"

I have tried both on older pushwoosh version (which I have a working build in production with), 6.1.18, and also on the latest version 6.1.27. 
Both encounter the same issue.

Could someone please init a new RN project and let me know if push notifications work?

### Bug severity

Urgent

### Steps to Reproduce

1. Initialize new RN project
2. Install pushwoosh-react-native-plugin, follow documentation for setup
3. check if you can register and receive token
4. check if you can register token to device on pushwoosh website
5. check if you can receive push notification on iOS through Test notification from website

### Your Pushwoosh React Native Plugin version

6.1.28

### Affected platforms

- [ ] Android
- [X] iOS

### Affected OS versions and/or devices

iOS 17.3.1, iPhone 13

**Comment by enginseer-dev** [comment]
@AlbinNewSeed hi there! Could you please contact our support at help@pushwoosh.com? Provide the device identifiers (HWID, UserID, or Push Token) you're trying to register, along with the logs from the device. Here's how to get console logs and the device token: [How to obtain console logs and device token](https://help.pushwoosh.com/hc/en-us/articles/360000292586-How-to-obtain-console-logs-and-device-token). Our support team will assist you further. Thanks!

**Comment by AlbinNewSeed** [comment]
> @AlbinNewSeed hi there! Could you please contact our support at [help@pushwoosh.com](mailto:help@pushwoosh.com)? Provide the device identifiers (HWID, UserID, or Push Token) you're trying to register, along with the logs from the device. Here's how to get console logs and the device token: [How to obtain console logs and device token](https://help.pushwoosh.com/hc/en-us/articles/360000292586-How-to-obtain-console-logs-and-device-token). Our support team will assist you further. Thanks!

Ok, will do, thanks!

**Comment by akidisdev** [comment]
@AlbinNewSeed as we discussed via the support case, the mismatch of iOS gateways caused the initial issue. We also suggested an upgrade of the Pushwoosh plugin to the latest version [6.1.30](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/6.1.30) to resolve the PushwooshPlugin window error you encountered. We'll close this issue, however, if you need additional assistance, please feel free to start a new one or reach out to our support at help@pushwoosh.com.
