### ISSUE TITLE
Existing app closes after installing Pushwoosh

### ISSUE THREAD

**Issue by vtisnado** [Pushwoosh/pushwoosh-react-native-plugin#16]
Hi guys, I tested the package in a clean app and it works fine, however when I try to add pushwoosh-react-native-plugin to my existing app, it closes on start and never fire an error. 

I suspect may be a conflict with react-native-google-analytics-bridge or react-native-firebase packages, but can't fine anything.

This is the content of my packages.json:

```
{
    "name": "Myapp",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest"
    },
    "dependencies": {
        "MD5": "^1.3.0",
        "moment": "^2.18.1",
        "native-base": "^2.3.2",
        "pushwoosh-react-native-plugin": "^3.1.0",
        "react": "16.0.0-alpha.12",
        "react-native": "0.48.3",
        "react-native-fetch-blob": "^0.10.8",
        "react-native-firebase": "^3.0.3",
        "react-native-google-analytics-bridge": "^5.3.3",
        "react-native-htmlview": "^0.12.0",
        "react-native-img-cache": "^1.4.0",
        "react-native-offline": "^3.1.1",
        "react-native-progress": "^3.4.0",
        "react-native-timeago": "^0.3.0",
        "react-native-video": "^2.0.0",
        "react-navigation": "^1.0.0-beta.11",
        "rn-placeholder": "^1.0.1"
    },
    "devDependencies": {
        "babel-jest": "21.0.2",
        "babel-preset-react-native": "4.0.0",
        "jest": "21.1.0",
        "react-test-renderer": "16.0.0-alpha.12"
    },
    "jest": {
        "preset": "react-native"
    }
}
```

More details here https://stackoverflow.com/questions/47478437/react-native-app-closes-after-installing-pushwoosh-package

**Comment by wfhm** [comment]
Hi,

Could you please share your application start device logs (including the moment when app closes)?

**Comment by vtisnado** [comment]
Hi @wfhm I just fixed the error adding these lines in my **android/app/build.gradle** file:

> compile("com.google.android.gms:play-services-gcm:11.4.2"){
>             force = true
>         }
>         compile("com.google.android.gms:play-services-location:11.4.2"){
>             force = true
>         }

I updated the Stackoverflow question to let others know how to fix this in the future.
