### ISSUE TITLE
[Bug]: TypeError: Cannot read property 'init' of null, js engine: hermes 

### ISSUE THREAD

**Issue by davortrifunov** [Pushwoosh/pushwoosh-react-native-plugin#169]
### Documentation

- [x] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

When trying to initialize Pushwoosh I am getting the following error:
`ERROR  TypeError: Cannot read property 'init' of null, js engine: hermes `

### Bug severity

Urgent

### Steps to Reproduce

1. Install latest pushwoosh-react-native-plugin: 6.1.33
2. Run iOS project

### Your Pushwoosh React Native Plugin version

6.1.32

### Affected platforms

- [ ] Android
- [X] iOS

### Affected OS versions and/or devices

Tested on iOS Simulator iPhone 14 Pro Max

**Comment by enginseer-dev** [comment]
Hello, @davortrifunov 

The Pushwoosh module was renamed to PushwooshFramework in the latest release:
https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/6.1.33

To fix the issue, please, go to "Targets" -> "NotificationService" -> "Frameworks and Libraries".
Delete the old "Pushwoosh.xcframework" and add "PushwooshFramework.xcframework":

![Screenshot 2024-09-25 at 20 52 45](https://github.com/user-attachments/assets/87f079a3-1df5-45a5-9e19-353d81dde2db)

**Comment by enginseer-dev** [comment]
Hello, @davortrifunov

The Pushwoosh module was renamed to PushwooshFramework in the latest release:
https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/6.1.33

To fix the issue, please, go to "Targets" -> "NotificationService" -> "Frameworks and Libraries".
Delete the old "Pushwoosh.xcframework" and add "PushwooshFramework.xcframework":

![Screenshot 2024-09-25 at 21 15 43](https://github.com/user-attachments/assets/852bd5a5-2f02-4798-b0ef-30c1055b5c9d)

Also please note that now API token from your Pushwoosh control panel needs to be added in the info.plist file with string value and "PW_API_TOKEN" key. To official manuals are going to be updated soon.

Please update us on the result.

**Comment by davortrifunov** [comment]
@enginseer-dev what if this plugin is used in combination with pushwoosh-expo-plugin?

**Comment by enginseer-dev** [comment]
@davortrifunov The same needs to be done - API key from Pushwoosh control panel needs to be entered into the info.plist file with "PW_API_TOKEN" key and "String" data type:

![image](https://github.com/user-attachments/assets/fd61fce5-aa2d-4ca2-8991-7461b6a58a1c)

I've tried to reproduce the issue by updating the Pushwoosh React Native plugin to 6.1.33 version in our Expo sample project - Pushwoosh initializes without any issues. Can you please try to enter the API key into your info.plist file and update us on the result?

**Comment by enginseer-dev** [comment]
@davortrifunov I have a follow-up question regarding the issue - do you use "npx expo prebuild" option?

**Comment by davortrifunov** [comment]
@enginseer-dev  yes, I added the pw_api_token in both info.plist with prebuild and in app.json. I am still getting the same error.

**Comment by enginseer-dev** [comment]
Hello, @davortrifunov 

We haven't heard from you in the last two weeks, so we are closing this issue for now. If you are still experiencing the problem, please feel free to reach out with a step-by-step guide on how you are building and launching the iOS project. 

We’ll be happy to assist further.
