### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by stereodenis** [Pushwoosh/pushwoosh-react-native-plugin#18]
There is no podspec to add this library via Pods

**Comment by wfhm** [comment]
Hi,

Could you please elaborate on this issue? What exactly do you want to achieve with using a React Native plugin with Cocoapods?

**Comment by stereodenis** [comment]
@wfhm I don't know is this enough for installing via cocoapods #19

**Comment by wfhm** [comment]
@stereodenis checked and merged.
