### ISSUE TITLE
App does not react to push when in foreground+iPhone locked on ios11

### ISSUE THREAD

**Issue by hanakivan** [Pushwoosh/pushwoosh-react-native-plugin#20]
Here is what is going on,

The plugin works fine except for this situation:
- your application is open and active in the foreground
- you lock your iphone
- you receive a push notification and swipe it, enter passcode or touchId
- the notification has already been in the foreground
- but events: either pushReceived nor pushOpened are emited

iPhone 8, ios11.2.5, react-native 0.45.1
- this is not working only on ios11, ios10 works fine.

Any ideas?

**Comment by wfhm** [comment]
Hi,

Checking it.

**Comment by wfhm** [comment]
Got it reproduced, working on a fix right now.

**Comment by wfhm** [comment]
Fixed in 5.5.6.
