### ISSUE TITLE
Android - Could not invoke Pushwoosh.init

### ISSUE THREAD

**Issue by nicholasc** [Pushwoosh/pushwoosh-react-native-plugin#21]
Hello,

I'm having an issue running my app on Android. I followed the installation instructions (install & link) and the package works perfectly on iOS. I also checked that my build.gradle was using version 26+ of the android sdk.

Using this simple init code:
```js
Pushwoosh.init({
  pw_appid: appId,
  project_number: projectNumber
});
```

I get the following error on the first load after building my app:
<img width="448" alt="screen shot 2018-03-28 at 10 43 39 am" src="https://user-images.githubusercontent.com/2378304/38036577-ff5aa2cc-3274-11e8-8cb5-8b66c5cd8742.png">

If I simply refresh, the error changes to this:
<img width="447" alt="screen shot 2018-03-28 at 10 44 03 am" src="https://user-images.githubusercontent.com/2378304/38036578-ff84d858-3274-11e8-84e7-2e7989e953f7.png">

Any help would be greatly appreciated.
Thank you!

**Comment by 8of** [comment]
@nicholasc 
Hello, Nicholas .
Can you specify Pushwoosh plugin version, please?
Where did you put `Pushwoosh.init` call in your app?

**Comment by nicholasc** [comment]
Hi @8of,

The version I currently use is `5.5.3` and the `Pushwoosh.init` call is in my `src/index.js` file. I tried to put it in my app's main component on `componentWillMount` but the same error is produced.

**Comment by nicholasc** [comment]
Upgrading to `5.5.7` fixed it. I suspect that the fix internally is linked to the android sdk version upgrades.

**Comment by 8of** [comment]
@nicholasc isn't there a warning / error on `5.5.7` about minimal supported iOS version === 10 when you try to archive iOS version?

**Comment by bernabe9** [comment]
Im having the same issue on Android with the version `5.5.7`

@nicholasc did you change something else to make it work?

**Comment by nicholasc** [comment]
@bernabe9 no, the update was all I needed. I guess you already know, but you have to make sure you use a project number.

@8of I haven't tried to build an Archive on iOS for version 10 since then. Is there an issue there that I should be aware of?

**Comment by 8of** [comment]
@nicholasc The issue comes into play if you need to support iOS versions prior 10.
App builds fine on simulator, but failing when you try to create app archive for AppStore.

When you try to archive project with PushWoosh plugin `5.5.6` or `5.5.7`, the process is failing with error about minimum supported library version of iOS 10.

**Comment by wfhm** [comment]
@8of Could you please create a new issue for this archive error with a bit more detailed description?

@bernabe9 Could not reproduce the issue with the latest plugin version. Could you please specify how and where exactly you initialize Pushwoosh lib?

**Comment by bernabe9** [comment]
@wfhm nvm, I don't know why `react-native link` didn't include the pushwoosh package in my `MainApplication.java`.

The last version works great! Thanks for the help

**Comment by nicholasc** [comment]
@wfhm I created issue #22 for the archiving problem @8of mentionned.
