### ISSUE TITLE
Android Build Fails

### ISSUE THREAD

**Issue by nicholasc** [Pushwoosh/pushwoosh-react-native-plugin#26]
I updated to the most recent version and whenever the Pushwoosh plugin is present I get this compilation error on Android: 

```
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [/Users/*****/*****/android/app/build/
intermediates/multi-dex/debug/componentClasses.jar] (Can't read [/Users
/*****/.gradle/caches/transforms-1/files-1.1/support-core-ui-27.1.1.aar/
10ef497bc88d4fd17626c7c50fff5bb0/jars/classes.jar(;;;;;;**.class)] 
(Duplicate zip entry [classes.jar:android/support/design/widget
/CoordinatorLayout$Behavior.class]))
```

iOS works fine. No matter what version of the play service & firebase I  use to compile, it systematically fails.

**Comment by wfhm** [comment]
Hi,

pushwoosh-react-native-plugin specifies `compile "com.android.support:design:26.+"` (and other parts of Android Support library). It looks like there is another plugin in your project which requires a different version (most likely, 27.+), so could you please check other third party plugins whether they also use it? As a temporary workaround, you can try locally editing plugin's build.gradle to have similar versions of Android Support lib across all your plugins.

**Comment by nicholasc** [comment]
I don't have a plugin that uses `com.android.support:design` except for pushwoosh-react-native-plugin. Changing from 26.+ to 27.+ worked for me.
