### ISSUE TITLE
Not able to upgrade to latest version.  5.8.0

### ISSUE THREAD

**Issue by RORrvtech** [Pushwoosh/pushwoosh-react-native-plugin#33]
> Task :pushwoosh-react-native-plugin:compileDebugJavaWithJavac FAILED
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:18: error: cannot find symbol
import com.pushwoosh.GDPRManager;
                    ^
  symbol:   class GDPRManager
  location: package com.pushwoosh
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/InboxUiStyleManager.java:77: error: cannot find symbol
            PWInboxStyle.setDefaultImageIconDrawable(defaultImageIcon);
                        ^
  symbol:   method setDefaultImageIconDrawable(Drawable)
  location: variable PWInboxStyle of type PushwooshInboxStyle
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/InboxUiStyleManager.java:81: error: cannot find symbol
            PWInboxStyle.setListErrorImageDrawable(listErrorImage);
                        ^
  symbol:   method setListErrorImageDrawable(Drawable)
  location: variable PWInboxStyle of type PushwooshInboxStyle
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/InboxUiStyleManager.java:85: error: cannot find symbol
            PWInboxStyle.setListEmptyImageDrawable(listEmptyImage);
                        ^
  symbol:   method setListEmptyImageDrawable(Drawable)
  location: variable PWInboxStyle of type PushwooshInboxStyle
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:311: error: cannot find symbol
                GDPRManager.getInstance().showGDPRConsentUI();
                ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:316: error: cannot find symbol
                GDPRManager.getInstance().showGDPRDeletionUI();
                ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:321: error: cannot find symbol
                success.invoke(GDPRManager.getInstance().isDeviceDataRemoved());
                               ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:326: error: cannot find symbol
                success.invoke(GDPRManager.getInstance().isCommunicationEnabled());
                               ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:331: error: cannot find symbol
                success.invoke(GDPRManager.getInstance().isAvailable());
                               ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:336: error: cannot find symbol
                GDPRManager.getInstance().setCommunicationEnabled(enable, new com.pushwoosh.function.Callback<Void, PushwooshException>() {
                ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
/Users/user/Documents/apps/MaxSecurity/node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/PushwooshPlugin.java:354: error: cannot find symbol
                GDPRManager.getInstance().removeAllDeviceData(new com.pushwoosh.function.Callback<Void, PushwooshException>() {
                ^
  symbol:   variable GDPRManager
  location: class PushwooshPlugin
11 errors

FAILURE: Build failed with an exception.

**Comment by wfhm** [comment]
Checking this one.

**Comment by RORrvtech** [comment]
Hello No after closing Metro bundler it doesn't fix, I Tried to clear cache and watchman.

But the Restarting system worked. Thanks for your attention

**Comment by RORrvtech** [comment]
Can you please let me know why events are not working
DeviceEventEmitter.addListener('pushReceived', (e: Event) => {
      infoLog("pushReceived: " + JSON.stringify(e));
      // shows a push is received. Implement passive reaction to a push, such as UI update or data download.
    });

    // this event is fired when user clicks on notification
    DeviceEventEmitter.addListener('pushOpened', (e: Event) => {
      infoLog("DeviceEventEmitter::pushOpened: ")
    });


Here push receive was firing correctly but, push opened never firing.
I am not sure how to debug this. Both iOS and android.
