### ISSUE TITLE
Pushwoosh with deep linking Manifest not working

### ISSUE THREAD

**Issue by RORrvtech** [Pushwoosh/pushwoosh-react-native-plugin#34]
When Implementing simple deepliking "https://medium.com/react-native-training/deep-linking-your-react-native-app-d87c39a1ad5e" 
You add following lines to manifest then Android "pushOpened" event never calls
Remove these lines pushOpen works like a charm.

:( 

 `
<intent-filter android:label="filter_react_native">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="myactivity" /> 
 </intent-filter>
`

**Comment by RORrvtech** [comment]
is somebody that side?

**Comment by wfhm** [comment]
@RORrvtech hi,

checking it.

**Comment by rajputav** [comment]
pinging for an update on this...

**Comment by wfhm** [comment]
@rajputav @RORrvtech We are working on a new version of React Native plugin, which will work with [React Native Linking](https://facebook.github.io/react-native/docs/linking). Once it is released, I will let you know.

**Comment by wfhm** [comment]
@RORrvtech @rajputav 

The plugin now works correctly with React Native Linking. The only thing to note is to call its methods **after Pushwoosh is initialized**.

**Comment by Shobanabohs100** [comment]
Hi @wfhm ,

I wonder what is the solution for the pushwoosh to work in android. can you add more information here? That would be more helpful.
