### ISSUE TITLE
v5.8.0 fails yarn install

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [Pushwoosh/pushwoosh-react-native-plugin#35]
pushwoosh-react-native-plugin: `v5.8.0`
OS: `OSX 10.13.5`
node: `v10.4.0`
npm: `v6.1.0`
yarn: `v1.9.4`
react-native: `v0.55.4`

`An unexpected error occurred: "ENOTDIR: not a directory, lstat '/Users/.../node_modules/pushwoosh-react-native-plugin/src/ios/PushwooshInboxBundle.bundle/PWIInboxViewController.nib/runtime.nib'".`

**Comment by wfhm** [comment]
Hi @jacobcabantomski-ct ,

I was able to successfully install the plugin with the following:

OS: `OSX 10.13.4`
node: `v10.9.0`
npm: `v6.2.0`
yarn: `v1.9.4`
react-native: `v0.56.0`

Could you please let us know whether the issue persists and if you can reproduce it with environment similar to mine?

**Comment by jacobcabantomski-ct** [comment]
@wfhm Finally got back to this and was able to successfully install & run after the following steps:

- `rm -rf ./node_modules`
- `yarn cache clean --all`
- `nvm install 10` <- node `v10.10.0`
- `yarn install`

Thanks for the response.
