### ISSUE TITLE
Pushwoosh react-native plugin compatibility with FCM

### ISSUE THREAD

**Issue by rajputav** [Pushwoosh/pushwoosh-react-native-plugin#38]
In the documentation I see: 
```
Pushwoosh.init({ 
    "pw_appid" : "YOUR_PUSHWOOSH_PROJECT_ID" , 
    "project_number" : "YOUR_GCM_PROJECT_NUMBER" 
});
```
However, according to https://developers.google.com/cloud-messaging/faq, Google is deprecating GCM in favor of Firebase Cloud Messaging. Does this plugin support FCM?

**Comment by rajputav** [comment]
how do we integrate FCM with this pushwoosh plugin? I don't see any documentation referencing FCM?

**Comment by rajputav** [comment]
@wfhm is there any documentation i'm missing on integrating FCM with this pushwoosh library? I don't see any documentation for it...

**Comment by efstathiosntonas** [comment]
According to build.gradle the plugin implements FCM so basically all you need is the FCM api key, then the plugin takes care of the rest.

https://github.com/Pushwoosh/pushwoosh-react-native-plugin/blob/master/src/android/build.gradle
