### ISSUE TITLE
[Android] setApplicationIconBadgeNumber crashes app

### ISSUE THREAD

**Issue by lorenc-tomasz** [Pushwoosh/pushwoosh-react-native-plugin#39]
Attempt to invoke virtual method 'void com.pushwoosh.badge.c.a.a(int)' on a null object reference
setBadgeNumber
    null:4
setApplicationIconBadgeNumber
    PushwooshPlugin.java:289
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:193
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764

**Comment by wfhm** [comment]
Hi @lorenc-tomasz ,

Checking it.

**Comment by lorenc-tomasz** [comment]
Hi @wfhm 

unfortunately this error randomly occurs. It's hard to reproduce it. Hope you will now where to search :) Good luck. 

Tested on pixel with Android 8.x

**Comment by lorenc-tomasz** [comment]
Any progress?

**Comment by wfhm** [comment]
@lorenc-tomasz Not yet. We were unable to reproduce the issue so far, so there is no understanding why it happens. We are going to refactor badges functionality first, and only after that we will be able to proceed with this task.

**Comment by wfhm** [comment]
We've reworked badges functionality in 5.11.0, however since the issue was not initially reproducible, we cannot guarantee it was fixed. May I ask you to try updating and let us know about the results?

**Comment by lorenc-tomasz** [comment]
Will try latter this week.

**Comment by wfhm** [comment]
@lorenc-tomasz any news on this one?

**Comment by lorenc-tomasz** [comment]
@wfhm Will test it on Monday. Is it OK with you?

**Comment by wfhm** [comment]
@lorenc-tomasz sure.

**Comment by lorenc-tomasz** [comment]
No crashes from yesterday. Will test it till Friday. It there will be no issues I will close the ticket.

**Comment by kotomono** [comment]
what is the correct way to show icon badges received from pushwoosh?
 if i set +1 on "ios_badges" and "android_badges", according to documentation, i should be able to see the badge but nothing happens when i receive the notification; at the moment the only code i put in App.js is:
> Pushwoosh.setApplicationIconBadgeNumber(0);
so that when i open the app i can clear the badges.
but as i said i see nothing on the app icon.

Thanks

**Comment by wfhm** [comment]
@kotomono 

> what is the correct way to show icon badges received from pushwoosh?
if i set +1 on "ios_badges" and "android_badges", according to documentation, i should be able to see the badge but nothing happens when i receive the notification; at the moment the only code i put in App.js is

Just checked it with the latest plugin version, everything works just fine. Could you please share your device log when receiving (and opening) a push? Can you see a badge value in push payload, like in the example below?

```
testRNProject[714:240872] pushReceived: {"aps":{"badge":20,"sound":"default","alert":"test ios badge react native"},"p":"3#G"}
```

**Comment by kotomono** [comment]
i sent 2 pushes:

> default	14:46:23.678754 +0100	SpringBoard	[testappname] Received remote notification request FB87-9DCF [ hasAlertContent: 1, hasSound: 1 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 0 ]
> default	14:46:23.682095 +0100	SpringBoard	[testappname] Badge can be set for notification FB87-9DCF: 0 [ canBadge: 1 badgeNumber: (null) ]
> default	14:46:24.101058 +0100	SpringBoard	[testappname] Received remote notification request 584C-B109 [ hasAlertContent: 1, hasSound: 1 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 0 ]
> default	14:46:24.101348 +0100	SpringBoard	[testappname] Badge can be set for notification 584C-B109: 0 [ canBadge: 1 badgeNumber: (null) ]

then i opened the app (there's Pushwoosh.setApplicationIconBadgeNumber(0); when i open the application)

> default	14:50:17.184535 +0100	testappname	[testappname] Setting badge number to 0
> default	14:50:17.187417 +0100	SpringBoard	[testappname] Setting badge to (null) [ old badge: (null) ]
> default	14:50:17.188019 +0100	SpringBoard	[FBSystemService] SpringBoard:52 requested the badge value for testappname be set to "(null)"
> default	14:50:17.195343 +0100	testappname	[testappname] Set badge number [ hasCompletionHandler: 0 hasError: 0 ]
> default	14:50:17.238109 +0100	testappname	[PW] [I] -[PWRequestManager] 
> x
> |    Pushwoosh request:
> | Url:      https://84AB1-84D35.api.pushwoosh.com/json/1.3/setBadge
> | Payload:  {"request":{"device_type":1,"badge":0,"application":"84AB1-84D35","userId":"DEFB2323-04C8-4246-8B11-F79F77FAF00C","v":"5.11.0","hwid":"DEFB2323-04C8-4246-8B11-F79F77FAF00C"}}
> | Status:   "200 no error"
> | Response: {"status_code":200,"status_message":"OK","response":null}
> x
> default	14:50:17.238329 +0100	testappname	[PW] [D] -[PWDataManagerCommon] setBadges completed
> 

no badges appear on the icon

**Comment by wfhm** [comment]
@kotomono so, according to the payload, there was no badge value specified for this push. May I ask you to share your /createMessage API request body?

**Comment by lorenc-tomasz** [comment]
You set Pushwoosh.setApplicationIconBadgeNumber(0); so you set 0. Zero means no badge on icon.

**Comment by wfhm** [comment]
@lorenc-tomasz this method will only be called after a user opens the app. Badge value should still be updated when receiving a push. So there is the issue with the push itself.

**Comment by lorenc-tomasz** [comment]
True.

**Comment by kotomono** [comment]
solved thank you. it was a problem on the createmessage
