### ISSUE TITLE
Enable multiple notifications in Android and IOS

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [Pushwoosh/pushwoosh-react-native-plugin#4]
Currently all my notifications get replaced with the new one. How can i enable multiple notifcations. Also i want the notifcation badge on the app icon in IOS to automatically set count based on notifications how can i achieve that with react-native pushwoosh plugin.

**Comment by wfhm** [comment]
Hi,

Both badges and multi-notification mode are not yet supported in our react native plugin, however we've already put it in our pipeline, so it's gonna be added soon.

**Comment by DimanAM** [comment]
[setMultiNotificationMode](http://docs.pushwoosh.com/docs/reactnative-api-reference#section-setmultinotificationmode) and [setApplicationIconBadgeNumber](http://docs.pushwoosh.com/docs/reactnative-api-reference#section-setapplicationiconbadgenumber) were added in 2.0.0 for this purpose.
