### ISSUE TITLE
Set tag not working in ios 

### ISSUE THREAD

**Issue by udaypratapsingh** [Pushwoosh/pushwoosh-react-native-plugin#43]
i am setting the tags as {
    "white_clarity" =     (
        VVS1,
        SI3,
        VVS2,
        I1
    );
    "white_color" =     (
        E,
        J,
        K,
        F
    );
    "white_lab" =     (
        HRD,
        AGS,
        IGI
    );
    "white_shape" =     (
        PEAR,
        EMERALD,
        PRINCESS
    );
}

But getting this response with skipped three tags

Response: {"status_code":200,"status_message":"OK","response":{"skipped":[{"tag":"white_lab","reason":"Not found"},{"tag":"white_clarity","reason":"Not found"},{"tag":"white_color","reason":"Not found"}]}}

**Comment by wfhm** [comment]
@udaypratapsingh 

Could you please let us know if this issue is still persistent?

> "response":{"skipped":[{"tag":"white_lab","reason":"Not found"},{"tag":"white_clarity","reason":"Not found"},{"tag":"white_color","reason":"Not found"}]}}

This response indicates that there are no such tags registered on our backend, so could you please double-check that they exist and are of **List** type?

**Comment by wfhm** [comment]
@udaypratapsingh just checked it, everything works correctly for iOS.

I used hardcoded values for Tags, however it should works in general cases as well:

```
Pushwoosh.setTags({"white_clarity":["VVS1","SI3","VVS2","I1"],"white_color":["E","J","K","F"],"white_shape":["PEAR","EMERALD","PRINCESS"]})
```
