### ISSUE TITLE
[iOS] bitcode bundle could not be generated because libPushwooshPlugin.a was built without full bitcode

### ISSUE THREAD

**Issue by lorenc-tomasz** [Pushwoosh/pushwoosh-react-native-plugin#45]
On 5.11.0:

bitcode bundle could not be generated because '.../libPushwooshPlugin.a(PWGeozonesManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '../libPushwooshPlugin.a' for architecture armv7

**Comment by cdriscol** [comment]
also effected by this.  this also happened to us in a previous release of the ios sdk.  is it possible PW could build ios again with bitcode enabled, that would be excellent!

**Comment by kotomono** [comment]
news on this?

**Comment by wfhm** [comment]
@kotomono @lorenc-tomasz @cdriscol Checking it.

**Comment by thedrluke** [comment]
Any news? @wfhm thanks in advance.

**Comment by wfhm** [comment]
@thedrluke will be fixed with the next release.

**Comment by wfhm** [comment]
@lorenc-tomasz will be fixed with the upcoming release.

**Comment by wfhm** [comment]
@lorenc-tomasz fixed in 5.12.0
