### ISSUE TITLE
[android] getHwid returns a guid

### ISSUE THREAD

**Issue by kotomono** [Pushwoosh/pushwoosh-react-native-plugin#46]
hello,
the device registration and every initialization works fine; problem is that if i send a notification from pushwoosh panel, message history says "success" but i simply don't receive anything on android devices; (if i send it from firebase cm panel using the token given by pushwoosh.register it works as expected, also iOS notifications works perfectly from pushwoosh panel and both ios and android devices are correctly registered).
i just noticed that the function pushwoosh.gethwid in android returns a guid formatted like this: d78c0342-49a4-4d6e-b8c6-95353d15f946, but this is not what i was expecting as hwid for android should be formatted like this "a9f282012f5dce9e".  (ios, instead, returns a correct uppercase guid).
can this be the cause of the problem of not receiving pushes on android? how can i solve it?

thanks

**Comment by wfhm** [comment]
@kotomono,
Pushwoosh Android SDK does not use the format like ** a9f282012f5dce9e** anymore - HWID is now a generated now inside Pushwoosh SDK and the format you can see with the latest versions.
There might be various reasons for pushes not to be delivered when a device is correctly registered, and investigation process might require us to request sensitive data, such as your Account name, App IDs, Notification codes etc. Therefore, I would like to suggest you creating a support ticket by dropping an email to help@pushwoosh.com with a link to this issue. Our support engineers will make sure to pass the ticket to SDK team timely for the further investigation.
