### ISSUE TITLE
[Android] Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by lorenc-tomasz** [Pushwoosh/pushwoosh-react-native-plugin#48]
> Configure project :pushwoosh-react-native-plugin
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Will you change it?

**Comment by wfhm** [comment]
@lorenc-tomasz Just set up a task to change the remaining 'compile' configurations with 'implementation'/'api', it should not take long to be replaced.

**Comment by wfhm** [comment]
@lorenc-tomasz changed with the latest release.
