### ISSUE TITLE
Build Error for android

### ISSUE THREAD

**Issue by leehch0** [Pushwoosh/pushwoosh-react-native-plugin#5]
Hello.

I'm using pushwoosh-react-native-plugin 1.2.4 for android app.
The following error has occurred

<./node_modules/pushwoosh-react-native-plugin/src/android/src/main/java/com/pushwoosh/reactnativeplugin/NotificationReceiver.java>:10: error: cannot find symbol
import com.pushwoosh.internal.utils.Log;

I think,
Log class was obfuscated on Pushwoosh Android SDK.
I cannot found Log class in pushwoosh.jar

**Comment by wfhm** [comment]
Hi,

We are looking into this issue, will come back to you as soon as there will be any news.

**Comment by wfhm** [comment]
Fixed via 1.2.5
