### ISSUE TITLE
[IOS] Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Sangrene** [Pushwoosh/pushwoosh-react-native-plugin#50]
I just upgraded this plugin from **5.9** to **5.12** and I can't compile anymore on iOS. 
Got the following error : 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PWGeozonesManager", referenced from:
      objc-class-ref in libpushwoosh-react-native-plugin.a(Pushwoosh.o)
ld: symbol(s) not found for architecture x86_64
```
**Environment:**
  OS: macOS 10.14
  Node: 10.13.0
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.0 AI-171.4443003

**Packages: (wanted => installed)**
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

**Comment by ASerga** [comment]
The same thing happens

**Comment by Sangrene** [comment]
I just rolled back to **5.9.1** as I don't see any changelog where I can find why I should try to update this plugin.

**Comment by travisgreermoguls** [comment]
@Sangrene - thanks for the heads up!  I had just run into this same issue (Xcode 10.1, RN 0.58.3, pushwoosh 5.12.0).  Using pushwoosh version 5.9.1 fixed the issue - hooray!

**Comment by wfhm** [comment]
@Sangrene @ASerga @travisgreermoguls checking it.

**Comment by wfhm** [comment]
@Sangrene are you using Cocoapods to link Pushwoosh plugin? The [podspec](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/blob/master/pushwoosh-react-native-plugin.podspec) is missing the geozones library, you should manually add PushwooshGeozones framework to it to fix the issue.

**Comment by Sangrene** [comment]
Yes, using Cocoapods. I will fix the podspec then.

Feel free to close my issue if you find that this isn't one !
