### ISSUE TITLE
[Android] Unreproducible builds and dependencies pushing the Dex limit

### ISSUE THREAD

**Issue by v4dkou** [Pushwoosh/pushwoosh-react-native-plugin#59]
https://github.com/Pushwoosh/pushwoosh-react-native-plugin/blob/master/src/android/build.gradle

There is a whole bunch of dependencies that are not required for most users, as they are specifically made for native UI development, and this is supposed to be a library for React Native.
```
implementation "com.android.support:recyclerview-v7:27.+"
implementation "com.android.support.constraint:constraint-layout:1.0.2"
```
Also, the "+" in dependency configurations is considered a poor practice, as it leads to unreproducible builds. In fact, I've only started to investigate, because an app that had worked just a month ago did not build yesterday, because the new versions of the libraries had fetched and we've hit the Dex limit.

I've excluded the Amazon module for now, as I know that the app will be only published to the Google Play, but I'd much rather get rid of the libraries for native UI development as there is absolutely no use for them.
```
    compile(project(':pushwoosh-react-native-plugin')) {
        exclude group: "com.pushwoosh", module: "pushwoosh-amazon"
    }
```

Please, fix your build.gradle

**Comment by wfhm** [comment]
Hello @v4dkou ,

These libraries are used for Inbox UI. Theoretically you can remove `com.pushwoosh:pushwoosh-inbox` and `com.pushwoosh:pushwoosh-inbox-ui` libs as well as mentioned above android-support dependencies, however we cannot guarantee it will work stable. As for '+' versions of dependencies, it intentionally used to prevent possible conflicts with other plugins that utilize play-services and android-support libs.

**Comment by v4dkou** [comment]
Hello @wfhm ,

`com.pushwoosh:pushwoosh-inbox-ui` is deployed as a separate package in native Android SDK for a reason: not all users need it. Please consider splitting the packages for React Native as well.
This would also improve build times for iOS users.

Speaking of '+' versions of dependencies: they **introduce** conflicts, rather than prevent them, as there may be older versions of these dependencies used in the app at some point, and the PushWoosh plugin forces the latest one to be downloaded _every time the project is built_.
Having CI/CD builds failing after a month without touching the codebase is frustrating to say the least.

You could add a way to select our own library versions via Gradle ext. variables.
Use this article for reference:
https://medium.com/@ivan_m/use-variables-to-manage-gradle-android-dependencies-library-version-numbers-92f0e362a2fc

For other users affected by this issue, I would recommend a workaround using Gradle ResolutionStrategy
https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

**Comment by wfhm** [comment]
@v4dkou 

> com.pushwoosh:pushwoosh-inbox-ui is deployed as a separate package in native Android SDK for a reason: not all users need it. Please consider splitting the packages for React Native as well.
This would also improve build times for iOS users.

Sure, this was already discussed within the team and it will most probably be done in the nearest future.

As for using ext., thank you for the suggestion. This indeed sounds like a solution to potential conflicts, however it leaves no possibility to specify default versions of dependencies, making integration more complicated. I will discuss it with the team and let you know if we will consider switching to using ext variables.

**Comment by v4dkou** [comment]
@wfhm What did the team say?
