### ISSUE TITLE
[security] Zip Path Traversal Vulnerability

### ISSUE THREAD

**Issue by noliiva** [Pushwoosh/pushwoosh-react-native-plugin#62]
Hello,
I got a message on google console that say there is a security issue on **com.pushwoosh.internal.utils.e.a** and a link to this article : https://support.google.com/faqs/answer/9294009
Can we hope a fix soon ?
Thank :)

**Comment by wfhm** [comment]
Hey @noliiva

Thanks for pointing this out!

Sure, we are working on it right at the moment, so it will be fixed with the upcoming release.

**Comment by wfhm** [comment]
Hi @noliiva,

Fixed it in the latest version of the Pushwoosh-React-Native plugin:

https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/5.14.1
