### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by TexxUkr** [Pushwoosh/pushwoosh-react-native-plugin#65]
The issue appears on compilation stage for android:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-31:19 to override.

Steps to reproduce:
- clone https://github.com/Pushwoosh/pushwoosh-react-native-sample.git
- yarn install
- adding google-services.json
- react-native run-android

OR
- react-native init test (RN - 0.59.9)
- yarn add pushwoosh-react-native-plugin
- react-native link 
- adding google-services.json
- react-native run-android

Additional: 
I have been using pushwoosh-react-native-plugin in my project for some period of time without issues but starting from today I am not able to build release anymore.

**Comment by wfhm** [comment]
Hi @TexxUkr,

Checking it

**Comment by JanithaR** [comment]
This is the source of this problem in the **build.gradle** file.

`implementation "com.google.firebase:firebase-core:+"`

**Comment by Sangrene** [comment]
This is due Google deploying new dependencies including breaking changes to android codebase (preparing androidx). The following `pushwoosh-react-native-plugin` dependencies are pulling the changes that break compiling :
```
com.google.firebase:firebase-core:+
com.google.firebase:firebase-messaging:+
```
You can update it by yourself or wait for [this PR](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/pull/64) to be merged.

**Comment by TexxUkr** [comment]
Thanks a lot JanithaR, Sangrene, wfhm!

Updating the dependencies solves the issue.
Will be waiting for the release as well.
Thanks

**Comment by JanithaR** [comment]
Alternatively, you could do the following changes to the /app/build.gradle file.
```
implementation (project(':pushwoosh-react-native-plugin')) {
       exclude group: 'com.google.firebase', module: 'firebase-core'
       exclude group: 'com.google.firebase', module: 'firebase-messaging'
}
implementation 'com.google.firebase:firebase-core:16.0.9'
implementation 'com.google.firebase:firebase-messaging:18.0.0'
```

**Comment by wfhm** [comment]
@JanithaR @Sangrene @TexxUkr

Fixed with the latest release.
