### ISSUE TITLE
0.60 compability

### ISSUE THREAD

**Issue by stereodenis** [Pushwoosh/pushwoosh-react-native-plugin#67]
`warn Package pushwoosh-react-native-plugin has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.ios.assets with value "["./src/ios/PushwooshInboxBundle.bundle"]" was found. This is either a typing error or a user mistake. Fixing it will remove this message.`

**Comment by wfhm** [comment]
Hi @stereodenis,

Please let me pull some time to check it.

**Comment by stereodenis** [comment]
@wfhm Got this
```
app_path/ios/Pods/pushwoosh-react-native-plugin/src/ios/PushwooshPlugin/PWEventDispatcher.h:9:9: 'React/RCTBridge.h' file not found

#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~


▸ Compiling pushwoosh-react-native-plugin-dummy.m
** BUILD FAILED **
```

**Comment by stereodenis** [comment]
```
ios/Pods/pushwoosh-react-native-plugin/src/ios/PushwooshPlugin/Pushwoosh.h:9:9: 'React/RCTBridgeModule.h' file not found

#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~


** BUILD FAILED **
```

**Comment by stereodenis** [comment]
@wfhm any news?

**Comment by wfhm** [comment]
@stereodenis,

This will be fixed with upcoming release.

**Comment by Return-1** [comment]
i am also experiencing this. any news on when the next release will be coming?

**Comment by wfhm** [comment]
@Return-1 @stereodenis,

Fixed with the latest release.
