### ISSUE TITLE
Is it possible to customize the push notifications?

### ISSUE THREAD

**Issue by JanithaR** [Pushwoosh/pushwoosh-react-native-plugin#69]
If not can we use something like [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) to show a customized notification? I'm not using `pushReceived` or `pushOpened` events, only deep linking.

**Comment by wfhm** [comment]
Hi @JanithaR,

Checking it

**Comment by wfhm** [comment]
@JanithaR,

This is possible, however, it will require native coding, particularly, creating a custom NotificationFactory class in a native Android project generated by React Native.

You can find more details in the docs below:

https://www.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk-5.0#customizing-push-notifications

You can also find an example of a native Android project with a custom NotificationFactory implemented in this repo:

https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Samples/Android-Advanced/app/src/main/java/com/pushwoosh/sample/NotificationFactorySample.java
