### ISSUE TITLE
Android show push notification on statusbar when app is in foreground

### ISSUE THREAD

**Issue by ilhamyputra** [Pushwoosh/pushwoosh-react-native-plugin#7]
Push notification doesn't appear on status bar when the app in running in foreground.
 I have added &lt;meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="true"/&gt;
but it still doesn't work.

https://community.pushwoosh.com/questions/4187/android-show-notification-on-status-bar-when-the-app-is-already-opened-and-receiving-push-notification

Thanks.

**Comment by wfhm** [comment]
Hi,

For Pushwoosh react native there is no out-of-the-box solution for your issue; `<meta-data android:name="PW_NO_BROADCAST_PUSH" android:value="true"/>` is only working for native Android apps and several other cross-platform frameworks at the moment. It will be supported for a react native plugin in the nearest future. As soon as it is done, we will update you in this thread and in the Community.

**Comment by DimanAM** [comment]
For React Native plugin you should use
```xml
<meta-data android:name="PW_BROADCAST_PUSH" android:value="false"/>
```

**Comment by 8of** [comment]
@DimanAM Can we reopen the issue, please?
Adding line 
```
<meta-data android:name="PW_BROADCAST_PUSH" android:value="false"/>
```
to manifest file with plugin version `5.5.6` has no effect and notification still doesn't appear on Android when app is in foreground.
Here is the reproducer:
https://github.com/8of/pushwoosh-react-native-sample

**Comment by wfhm** [comment]
@8of 

It should be specified with **"true"** value to make notifications appear in foreground:

```
<meta-data android:name="PW_BROADCAST_PUSH" android:value="true"/>
```

This was changed quite a while ago to make usage of this meta-data more "intuitive". Documentation is updated now:

https://www.pushwoosh.com/docs/react-native-plugin#section-push-notifications-in-foreground

**Comment by 8of** [comment]
@wfhm it works, thank you very much!
