### ISSUE TITLE
5.17.0 fix for RN 60 crashes android build

### ISSUE THREAD

**Issue by Return-1** [Pushwoosh/pushwoosh-react-native-plugin#71]
The newly released 5.17.0 version and android wont build. removing `pushwoosh-react-native-plugin `yields a succesful build.

A few potentially helpful pointers:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
19 actionable tasks: 6 executed, 13 up-to-date
```
also
```
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
[... reducted]
```

potentially refer to: #67

**Comment by wfhm** [comment]
Hi @Return-1,

Checking it.

**Comment by wfhm** [comment]
@Return-1,

Just to make sure, did you place **google-services.json** to your `android/app/` directory as per our guide? Is your app connected to a Firebase project for which this file was generated?

**Comment by Return-1** [comment]
On other projects im using this plugin the google-services.json is in place. In this one however i was attempting to only use the localNotification functionality and since the app is not connected to any Firebase project there is no google-services.json.

Is there a way around this so the localNotification functionality can work without creating a Firebase project?

**Comment by wfhm** [comment]
@Return-1 ,

The google-services.json file is required for initializing Pushwoosh SDK, so it should persist in your project. However you only need the file to exist in `android/app/` and to contain your application's package name, Sender ID value should not necessarily match any real Firebase project. However you will still need a Sender ID to call `Pushwoosh.init()`, so I still recommend connecting the app to Firebase.

**Comment by Return-1** [comment]
Thank you i will follow that approach. I think we can mark this as resolved.

One final question which im not sure where it is i need to address ( upon direction i shall delete this comment ). Creating a local notification yields no sound. Is there a way to do that? Nothing of the sort is shown in the documentation.

**Comment by wfhm** [comment]
@Return-1,

Just checked it and indeed there is no way to control sound in local notifications in React Native. Since controlling sounds is a bit off-topic, may I ask you to create a new issue in this repo for it?
