### ISSUE TITLE
iOS: Providing UNNotification callback delegate

### ISSUE THREAD

**Issue by BozidarK93** [Pushwoosh/pushwoosh-react-native-plugin#82]
When using Pushwoosh on iOS we can not receive any local notification callbacks since the shared UNNotification delegate is assigned in the init method. This means that I can not assign my own UNNotification delegate in order to get iOS UNNotificationCenterDelegate callback methods. 

Suggestion: 
Adding a new parameter in the config or exposing a new javascript method for setting the UNNotification delegate could be one of the possible approaches.
If there is an interest in this feature I can make a PR.

**Comment by BozidarK93** [comment]
Than I could achieve something like the following https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/65

**Comment by wfhm** [comment]
Hi @BozidarK93,

Let me pull some time to review the information that you have provided. I will get back to you soon.

Please stay tuned.

**Comment by wfhm** [comment]
@BozidarK93,

I've discussed it with the team and we'd be happy to see a PR adding this feature. Thanks in advance!

**Comment by p01nicoaurev** [comment]
@wfhm Any update on this? :)

**Comment by nikolleto** [comment]
@BozidarK93 @p01nicoaurev PR has just been merged. Thank you greatly for collaboration.

**Comment by p01nicoaurev** [comment]
@nikolleto what SDK version this implementation will be available?

**Comment by wfhm** [comment]
@p01nicoaurev 

It is available starting with 6.0.2 version of pushwoosh-react-native-plugin. To use it, just specify `"pw_notification_handling":"CUSTOM"` in Pushwoosh.init() method params.

**Comment by p01nicoaurev** [comment]
How about for iOS not in react native?
