### ISSUE TITLE
iOS: iPhone 11: Invalid Token

### ISSUE THREAD

**Issue by nicholasc** [Pushwoosh/pushwoosh-react-native-plugin#85]
The `register` method does not seem to work on the new iPhone 11. Everytime we attempt to register a device we get the following error: 

`Invalid token: {length=32,bytes=0x20d221c1af57f1b5165c8089fbb07090...d78f0b081ea5bfd0}`. 

Pushwoosh's native code might be using something to register the device that is different on an iPhone 11 and may be causing the token to break?

Other devices have been tested and function properly. 
We're using the latest version of this library.

**Comment by wfhm** [comment]
Hi @nicholasc,

 May I ask you to let me know the version of Pushwoosh SDK you are using in your application?

**Comment by nicholasc** [comment]
pushwoosh-react-native-plugin: 5.18.1
Pushwoosh/Core: 5.13.0

**Comment by wfhm** [comment]
@nicholasc,

The issue is already fixed with 5.16.0 release. It looks like your pods are not properly updated with the plugin update, so may I ask you to remove the pods and the plugin and reinstall it in your project?

**Comment by nicholasc** [comment]
Updating the pods to the latest version of the core library worked. Thank you.
