### ISSUE TITLE
pod install not working with use_frameworks!

### ISSUE THREAD

**Issue by EugeneDraitsev** [Pushwoosh/pushwoosh-react-native-plugin#87]
Hi, I faced with an issue with rn plugin.
I have default react-native-cli application Podfile and it works fine, but if I add `use_frameworks!` to Podfile then `pod install` throws this error:

```
[!] The 'Pods-AwesomeProject' target has transitive dependencies that include statically linked binaries: 

(/Users/eudr1/environment/AwesomeProject/ios/Pods/Pushwoosh/Framework/Pushwoosh.framework and
 /Users/eudr1/environment/AwesomeProject/ios/Pods/PushwooshInboxUI/Framework/PushwooshInboxUI.framework)
```

Steps to reproduce: 
1. npx react-native init AwesomeProject
2. yarn add pushwoosh-react-native-plugin
3. add use_frameworks! to the end of target in Podfile
4. run pod install

**Comment by wfhm** [comment]
Hi @EugeneDraitsev,

Checking it!

**Comment by wfhm** [comment]
@EugeneDraitsev,

Fixed with the latest release.
