### ISSUE TITLE
iOS Build: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mlnchk** [Pushwoosh/pushwoosh-react-native-plugin#89]
When i try to build iOS i had following issue:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UIWindowScene", referenced from:
      objc-class-ref in libPushwooshPlugin.a(libPushwoosh.a-x86_64-master.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

"pushwoosh-react-native-plugin": "^5.19.3"
"react-native": "0.59.10"
No CocoaPods, only react-native link

**Comment by wfhm** [comment]
Hi @mlnchk,

Could you please specify the version of Xcode you are using at the moment?

**Comment by mlnchk** [comment]
Xcode Version 10.2.1 (10E1001)

**Comment by wfhm** [comment]
@mlnchk

May I ask you to update the version of Xcode to the latest available and try to build your project again?

**Comment by mlnchk** [comment]
Oh, that works. 2 killed days and so simple solution.
Thank you!

May you explain, why this is happen?

**Comment by wfhm** [comment]
@mlnchk UIWindowScene class was initially added in iOS 13, which is shipped with Xcode 11.
