### ISSUE TITLE
No task registered for key RNFirebaseBackgroundMessage (Android)

### ISSUE THREAD

**Issue by ymcewen** [Pushwoosh/pushwoosh-react-native-plugin#94]
Hi There,

I've followed this guide (https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/integrating-react-native-plugin) on the website but it just isn't working in my project.

When I use the same init credentials in the example on GitHub, I get the notification.

My error is ```No task registered for key RNFirebaseBackgroundMessage```

I followed the example to the letter so not really sure whats going on. Ive seen some things online about the error but none seem to help.

Here is my index.js file:

```import { AppRegistry, Alert, BackHandler, DeviceEventEmitter, NativeEventEmitter, NativeModules } from 'react-native';
import App from './src/routes/routes';
import { name as appName } from './app.json';
import { setJSExceptionHandler, setNativeExceptionHandler } from 'react-native-exception-handler';
import firebase from 'react-native-firebase';

const reporter = (error) => {
    // Logic for reporting to devs
    // Example : Log issues to github issues using github apis.
    console.log(error); // sample
    firebase.crashlytics().log(error);
};

const errorHandler = (e, isFatal) => {
    if (isFatal) {
        reporter(e);
        Alert.alert(
            'Unexpected error occurred',
            `Error: ${(isFatal) ? 'Fatal:' : ''} ${e.name} ${e.message}
            We have reported this to our team ! Please close the app and start again!
            `,
            [{
                text: 'Close',
                onPress: () => {
                    BackHandler.exitApp();
                }
            }]
        );
    } else {
        firebase.crashlytics().log(e);
        console.log(e); // So that we can see it in the ADB logs in case of Android if needed
    }
};

setJSExceptionHandler(errorHandler);
setNativeExceptionHandler(exceptionString => { });

import Pushwoosh from 'pushwoosh-react-native-plugin';

AppRegistry.registerComponent(appName, () => App);

DeviceEventEmitter.addListener('pushOpened', (e) => {
    console.warn("pushOpened: " + JSON.stringify(e));
    alert(JSON.stringify(e));
  });

DeviceEventEmitter.addListener('pushReceived', (e) => {
console.warn("pushReceived: " + JSON.stringify(e));
// shows a push is received. Implement passive reaction to a push, such as UI update or data download.
});
  
  
  Pushwoosh.init({ "pw_appid" : "MY ID", "project_number":"MY NUMBER"});
  
  Pushwoosh.register(
    (token) => {
      console.warn("Registered for pushes: " + token);
      Pushwoosh.getPushToken(function(token) {
          console.warn("Push token: " + token);
  
          // Geolocation tracking example
          //PushwooshGeozones.startLocationTracking();
          //PushwooshGeozones.stopLocationTracking();
      });
    },
    (error) => {
      console.warn("Failed to register: " + error);
    }
  );
  
  Pushwoosh.getHwid((hwid) => {
    console.warn("Pushwoosh hwid: " + hwid);
  });```

**Comment by wfhm** [comment]
Hi @ymcewen, please let me pull some time to check it.

**Comment by wfhm** [comment]
@ymcewen,

Could you please share the complete crash log, package.json and AndroidManifest.xml?

**Comment by ymcewen** [comment]
Hi @wfhm 

I've now reverted my changes but to be clear- there was no crash. It was just a warning in the console when the push notification should have been received.

**Comment by wfhm** [comment]
@ymcewen,

Thank you for the clarification. From what I could find, it seems more like a warning from **react-native-firebase** rather than from Pushwoosh plugin. There might've been a conflict between FirebaseMessagingService classes added by both plugins, however I cannot say for sure without more information.

Also, were push notifications working as expected with this warning?

**Comment by ymcewen** [comment]
@wfhm no the push notification didn't come through. It was just the warning. I can confirm that I uncommented the code in the AndroidManifest.xml and I still didn't get the notification.

Would you advise me to remove this
```<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
  <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />```

We are(should) only be using Pushwoosh for notifications.

**Comment by wfhm** [comment]
@ymcewen,

The better solution would be creating a master FirebaseMessagingService, which will handle push received events and route it to Pushwoosh and Firebase FirebaseMessagingServices depending on push payload.

First, you have to create a new class inside the Pushwoosh plugin package:

    package com.pushwoosh.reactnativeplugin;

     import android.content.Context;

     import com.google.firebase.messaging.RemoteMessage;
     import com.pushwoosh.PushwooshFcmHelper;

     import javax.annotation.Nullable;

    public class PWFcmHelper extends PushwooshFcmHelper{
     public static void onTokenRefresh(Context context, @Nullable String token){
     super.onTokenRefresh(context, token);
     }
     public static boolean onMessageReceived(Context context, RemoteMessage message){
     super.onMessageReceived(context, message);
     }

     public static boolean isPushwooshMessage(RemoteMessage message){
     super.isPushwooshMessage(message);
     }
    }

After that, you need to create a master FirebaseMessagingService class in your main package and use the PWFcmHelper class instead of the PushwooshFcmHelper:

    import com.pushwoosh.reactnativeplugin.PWFcmHelper;

    public class MainMessagingService extends FirebaseMessagingService {
     private static final String _TAG_ = "MainMessagingService";

     @Override
     public void onMessageReceived(RemoteMessage remoteMessage) {

     if (PWFcmHelper.isPushwooshMessage(remoteMessage)) {
     //this is a Pushwoosh push, SDK will handle it automatically
     PWFcmHelper.onMessageReceived(this, remoteMessage);
     }else {
     //super.onMessageReceived(remoteMessage);
     //or your custom Firebase message handling logic
     }
     }
    }

Register this service in the AndroidManifest.xml with the highest priority:

            <service android:name="com.your.packagename.MainMessagingService">
                <intent-filter android:priority="500">
                    <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                </intent-filter>
            </service>

**Comment by ymcewen** [comment]
Thanks, will give this a shot and feedback

**Comment by wfhm** [comment]
@ymceven,

Any luck so far?

**Comment by ymcewen** [comment]
To be honest, I got a bit lost with where to add what as I’m not familiar with java or the structure of Rn plugins. 

What I did do though was remove all firebase messaging references in my code and this worked. 



> On 27 Jan 2020, at 8:41 am, wfhm <notifications@github.com> wrote:
> 

﻿
@ymceven,

Any luck so far?
