### ISSUE TITLE
Xcode build errors on 5.20.0+ (PWInlineInAppManager.h)

### ISSUE THREAD

**Issue by pbfrias17** [Pushwoosh/pushwoosh-react-native-plugin#95]
Followed the docs to install (yarn, pod install), but getting these build errors:
- PWInlineInAppManager.m:27:10: `Property 'delegate' not found on object of type 'PWReactInlineInAppView *'`
- PWInlineInAppManager.h:13:51: `Type argument 'PWInlineInAppView' must be a pointer (requires a '*')` ("fixable" be just appending * to the type within <>)

I also tried manually linking (add `PushwooshPlugin.xcodeproj` and link `libPushwooshPlugin.a`, that removed some errors but gave me another:
- Pushwoosh.h:23:9: `'PWInlineInAppView.h' file not found`

Im on RN 60.0 and these errors appear on all versions since 5.20.0 (5.19.7 builds fine)

**Comment by wfhm** [comment]
Hi @pbfrias17,

Could you please describe the exact steps to reproduce the issue? Also, does the `'PWInlineInAppView.h' file not found` error appear on the 5.20.2 version?
