### ISSUE TITLE
Implement iOS rich notifications with react-native

### ISSUE THREAD

**Issue by SimonErich** [Pushwoosh/pushwoosh-react-native-plugin#96]
Hello,

we are planning to implement ios rich notifications with this plugin in our react-native app.
Can I just copy/paste the code linked in this article in our app MainDelegate or is this baked into the plugin already?
https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/ios-push-notifications/ios-rich-notifications-integration

If so, how can we activate it properly?

Thank you

**Comment by wfhm** [comment]
Please let me check it first and I'll get back to you.

**Comment by wfhm** [comment]
// Assigned to Second Line queue as **question**.

Please add an internal comment with a detailed description of your question

**Comment by wfhm** [comment]
Hi @SimonErich,

I am sorry for the delayed response.

No, this is not working out of the box. You will need to modify your native iOS project, however, the code does not just go to the Delegate. You will need to create a Notification Service Extension and perform all the steps as described in the guide you linked.

**Comment by SimonErich** [comment]
@wfhm thank you for your response and sorry for my delayed answer, I was on holiday.
So I can just follow the iOS guide exactly and then it should work without a problem or is there something react-native specific I have to do as well?

**Comment by wfhm** [comment]
@SimonErich Yes, you can just follow the guide, there should be nothing specific to React Native.
